-- Insertar datos de cargos en la tabla cargos
-- Fecha: $(date)
-- Descripción: Script para insertar la lista completa de cargos disponibles

INSERT INTO cargos (nombre, descripcion) VALUES
('ADMINISTRATIVO', 'Personal encargado de tareas administrativas generales'),
('ANALISTA DE CRÉDITO', 'Profesional encargado del análisis y evaluación de créditos'),
('ANALISTA DE GARANTÍAS', 'Especialista en el análisis y gestión de garantías'),
('ANALISTA DE NÓMINA', 'Profesional responsable del procesamiento y análisis de nómina'),
('ANALISTA LOGÍSTICO ELECTRO', 'Especialista en logística del área de electrodomésticos'),
('ANALISTA LOGÍSTICO MOTOS', 'Especialista en logística del área de motocicletas'),
('APRENDIZ SENA ETAPA LECTIVA', 'Estudiante SENA en fase de formación teórica'),
('APRENDIZ SENA ETAPA PRODUCTIVA', 'Estudiante SENA en fase de práctica laboral'),
('ASESOR COMERCIAL', 'Profesional encargado de la asesoría y ventas comerciales'),
('ASESOR DE MAYOREO', 'Especialista en ventas al por mayor'),
('ASESOR ECOMMERCE', 'Profesional especializado en comercio electrónico'),
('ASESOR REPUESTOS', 'Especialista en asesoría y venta de repuestos'),
('ASESORA COMERCIAL', 'Profesional femenina encargada de asesoría comercial'),
('AUXILIAR CONTABLE', 'Asistente en tareas contables y financieras'),
('AUXILIAR CONTRATACIÓN', 'Asistente en procesos de contratación de personal'),
('AUXILIAR CONTROL INTERNO', 'Asistente en actividades de control interno'),
('AUXILIAR DE ARCHIVO', 'Encargado de la organización y mantenimiento de archivos'),
('AUXILIAR DE BODEGA', 'Asistente en operaciones de bodega y almacén'),
('AUXILIAR DE RECEPCIÓN', 'Encargado de atención en recepción'),
('AUXILIAR DE SERVICIOS GENERALES', 'Asistente en servicios generales y mantenimiento'),
('AUXILIAR DE SOPORTE', 'Asistente técnico en soporte y sistemas'),
('AUXILIAR SERVICIO AL CLIENTE', 'Asistente en atención al cliente'),
('AUXILIAR SERVICIOS GENERALES', 'Encargado de servicios generales y limpieza'),
('AUXILIAR TESORERÍA', 'Asistente en operaciones de tesorería'),
('BACKUP CRM', 'Encargado de respaldo y soporte del sistema CRM'),
('BODEGUERO/MENSAJERO', 'Trabajador de bodega con funciones de mensajería'),
('CAMARERA/RECEPCIONISTA', 'Personal de servicio y recepción'),
('COMMUNITY MANAGER', 'Especialista en gestión de redes sociales y comunidades'),
('COMPRADOR JUNIOR', 'Asistente en procesos de compras'),
('CONDUCTOR', 'Encargado del transporte y conducción de vehículos'),
('CONTADOR', 'Profesional contable responsable de la contabilidad'),
('COORDINADOR CALIDAD', 'Responsable de la coordinación de procesos de calidad'),
('COORDINADOR GESTIÓN DOCUMENTAL', 'Encargado de la gestión y organización documental'),
('COORDINADOR LOGÍSTICO', 'Responsable de la coordinación de operaciones logísticas'),
('COORDINADOR SEGURIDAD Y SALUD EN EL TRABAJO', 'Encargado de la coordinación de SST'),
('DEPENDIENTE JUDICIAL', 'Personal encargado de trámites y procesos judiciales'),
('DESARROLLADOR DE APLICACIONES', 'Programador especializado en desarrollo de aplicaciones'),
('DIRECTOR COMERCIAL', 'Directivo responsable del área comercial'),
('DIRECTOR CONTROL INTERNO', 'Directivo encargado del control interno organizacional'),
('DIRECTOR TALENTO HUMANO', 'Directivo responsable de la gestión del talento humano'),
('DISEÑADOR GRÁFICO', 'Profesional especializado en diseño gráfico'),
('DISEÑADOR WEB', 'Especialista en diseño y desarrollo web'),
('EJECUTIVO CENTRO DE SERVICIO Y RECAUDO', 'Ejecutivo de centros de servicio y recaudo'),
('FRONT', 'Personal de atención frontal al cliente'),
('GERENTE AGENCIA BDATAM', 'Gerente de la agencia BDATAM'),
('GERENTE COMERCIAL', 'Gerente del área comercial'),
('GERENTE DE ZONA', 'Gerente responsable de una zona específica'),
('GERENTE ORPA INVERSIONES', 'Gerente de ORPA Inversiones'),
('GERENTE SUPERNUMERARIO', 'Gerente en posición supernumeraria'),
('GERENTE TRADE MARKETING COMPRAS Y LOGÍSTICA', 'Gerente de trade marketing, compras y logística'),
('GESTOR DE CONTACT CENTER', 'Encargado de la gestión del centro de contacto'),
('GESTOR DE RECAUDO EXTERNO', 'Especialista en gestión de recaudo externo'),
('JEFE DE CENTRO DE SERVICIO', 'Jefe responsable del centro de servicio'),
('LAVADOR DE MOTOS', 'Encargado del lavado y limpieza de motocicletas'),
('LÍDER DE BODEGA', 'Líder responsable de las operaciones de bodega'),
('LÍDER DE REPUESTOS', 'Líder del área de repuestos'),
('LÍDER SERVICIO AL CLIENTE', 'Líder del equipo de servicio al cliente'),
('LÍDER TICS', 'Líder del área de tecnologías de información'),
('MENSAJERO', 'Encargado de servicios de mensajería'),
('PRODUCTOR MULTIMEDIA', 'Especialista en producción de contenido multimedia'),
('PSICÓLOGA DE SELECCIÓN Y BIENESTAR', 'Psicóloga especializada en selección y bienestar laboral'),
('SUPERNUMERARIO', 'Personal en posición supernumeraria'),
('TÉCNICO DE MOTOS', 'Técnico especializado en reparación de motocicletas'),
('TESORERÍA', 'Personal del área de tesorería'),
('EJECUTIVO CSR', 'Ejecutivo de responsabilidad social corporativa'),
('ASESOR ELECTRO', 'Asesor especializado en electrodomésticos'),
('ASESOR MOTOS 9', 'Asesor de motocicletas zona 9');

-- Verificar la inserción
SELECT COUNT(*) as total_cargos_insertados FROM cargos WHERE nombre IN (
    'ADMINISTRATIVO', 'ANALISTA DE CRÉDITO', 'ANALISTA DE GARANTÍAS', 'ANALISTA DE NÓMINA',
    'ANALISTA LOGÍSTICO ELECTRO', 'ANALISTA LOGÍSTICO MOTOS', 'APRENDIZ SENA ETAPA LECTIVA',
    'APRENDIZ SENA ETAPA PRODUCTIVA', 'ASESOR COMERCIAL', 'ASESOR DE MAYOREO', 'ASESOR ECOMMERCE',
    'ASESOR REPUESTOS', 'ASESORA COMERCIAL', 'AUXILIAR CONTABLE', 'AUXILIAR CONTRATACIÓN',
    'AUXILIAR CONTROL INTERNO', 'AUXILIAR DE ARCHIVO', 'AUXILIAR DE BODEGA', 'AUXILIAR DE RECEPCIÓN',
    'AUXILIAR DE SERVICIOS GENERALES', 'AUXILIAR DE SOPORTE', 'AUXILIAR SERVICIO AL CLIENTE',
    'AUXILIAR SERVICIOS GENERALES', 'AUXILIAR TESORERÍA', 'BACKUP CRM', 'BODEGUERO/MENSAJERO',
    'CAMARERA/RECEPCIONISTA', 'COMMUNITY MANAGER', 'COMPRADOR JUNIOR', 'CONDUCTOR', 'CONTADOR',
    'COORDINADOR CALIDAD', 'COORDINADOR GESTIÓN DOCUMENTAL', 'COORDINADOR LOGÍSTICO',
    'COORDINADOR SEGURIDAD Y SALUD EN EL TRABAJO', 'DEPENDIENTE JUDICIAL', 'DESARROLLADOR DE APLICACIONES',
    'DIRECTOR COMERCIAL', 'DIRECTOR CONTROL INTERNO', 'DIRECTOR TALENTO HUMANO', 'DISEÑADOR GRÁFICO',
    'DISEÑADOR WEB', 'EJECUTIVO CENTRO DE SERVICIO Y RECAUDO', 'FRONT', 'GERENTE AGENCIA BDATAM',
    'GERENTE COMERCIAL', 'GERENTE DE ZONA', 'GERENTE ORPA INVERSIONES', 'GERENTE SUPERNUMERARIO',
    'GERENTE TRADE MARKETING COMPRAS Y LOGÍSTICA', 'GESTOR DE CONTACT CENTER', 'GESTOR DE RECAUDO EXTERNO',
    'JEFE DE CENTRO DE SERVICIO', 'LAVADOR DE MOTOS', 'LÍDER DE BODEGA', 'LÍDER DE REPUESTOS',
    'LÍDER SERVICIO AL CLIENTE', 'LÍDER TICS', 'MENSAJERO', 'PRODUCTOR MULTIMEDIA',
    'PSICÓLOGA DE SELECCIÓN Y BIENESTAR', 'SUPERNUMERARIO', 'TÉCNICO DE MOTOS', 'TESORERÍA',
    'EJECUTIVO CSR', 'ASESOR ELECTRO', 'ASESOR MOTOS 9'
);

COMMIT;
